#!/bin/bash

echo "⚡🌴🌆 OMEGA STREAMING FEATURE DEMO 🌆🌴⚡"
echo ""
echo "Testing the new live thinking display!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NOTE: Streaming is ON by default in the new version!"
echo "You'll see the gAIng's thoughts appear in real-time as they think."
echo ""
echo "Press Enter to watch a quick demo..."
read

echo ""
echo "🎬 Running a simple mission with STREAMING ENABLED..."
echo ""

~/.local/bin/omega run "Say hello to the world"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Did you see it?"
echo ""
echo "Notice how:"
echo "  ⚡ Spinners animated while planning"
echo "  📝 Agent responses appeared character by character"
echo "  💫 You could watch their thinking process!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎮 Interactive Mode Commands:"
echo ""
echo "  omega              # Start Omega"
echo "  omega▸ stream on   # Enable live thinking (default)"
echo "  omega▸ stream off  # Use spinners only"
echo "  omega▸ agents      # See the gAIng roster"
echo "  omega▸ help        # All commands"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Pro Tip: Start interactive mode and try:"
echo ""
echo "   omega▸ stream on"
echo "   omega▸ Tell me a fun fact about AI"
echo ""
echo "Watch the magic happen! ✨"
echo ""
